### ISSUE TITLE
mit-scheme fails to build on 10.11

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew-x11#103]
[Gist](https://gist.github.com/aw1621107/8cadab27c77c59b99efa)

Build fails both `--without-x11` and no flags. Something about being unable to compute sizeof (intptr_t)?

Let me know if I can provide more info.

**Comment by aw1621107** [comment]
Hmmm, seems I didn't run `xcode-select --install` earlier... Build still fails, though, with some pretty strange config output...

[gist](https://gist.github.com/aw1621107/a3318fe28aab93a13e46)

**Comment by aw1621107** [comment]
Found it!

mit-scheme is hard-coded to look for /Applications/Xcode.app, which doesn't exist for beta versions. Symlinking /Applications/Xcode-beta.app to /Applications/Xcode.app did the trick, and I presume changing the configuration script to look for Xcode-beta if Xcode isn't there would do the same thing.

The line in question is in mit-scheme-c-9.2/src/microcode/configure:5478. If I can figure out how patching works I'll see if I can't submit something...

**Comment by MassimoLauria** [comment]
Should the build work also when I don't have XCode.all but just the command line tools installed in 
/Library/Developer/CommandLineTools ?

**Comment by aw1621107** [comment]
@MassimoLauria I'm not sure what exactly mit-scheme uses from xcode, but IIRC brew wouldn't let me build mit-scheme without it on 10.10

**Comment by vcarus** [comment]
Same problem with @aw1621107 

With only CLT fail to build, Xcode 7 fix it.
Thanks.

**Comment by DomT4** [comment]
If they've hardcoded it to look for Xcode on build you'll need to have that on the system, aye. It might be worth reporting this upstream and finding out what parts of Xcode they need and whether the CLT is enough by itself.

**Comment by DomT4** [comment]
Going to close this one out. There are a few formula that do this in the core and the advice is more or less if you encounter one, **symlink** the beta Xcode to `/Applications/Xcode.app`.

I've added a `xcode` build dependency so at least folks with the CLT installed and who try to install from source don't get magically elusive failure messages. You can still pour the bottle fine without needing Xcode.

Feel free to kick this upstream and ask if there's any way for them to remove the requirement on Xcode, which is a rather hefty requirement.

**Comment by aw1621107** [comment]
Submitted a bad feature request upstream, so hopefully it'll get fixed eventually
