### ISSUE TITLE
imake cannot exec cpp-5

### ISSUE THREAD

**Issue by shaomeng** [Homebrew/homebrew-x11#110]
imake reports "imake: Cannot exec /usr/local/Cellar/gcc/5.1.0/bin/cpp-5.". 

My system actually has gcc installed from homebrew, and it's 5.2 instead of 5.1:
/usr/local/bin/cpp-5 -> ../Cellar/gcc/5.2.0/bin/cpp-5

I guess directing imake to look for cpp-5 from /usr/local/bin would fix.

Thanks!

**Comment by dunn** [comment]
Looks like we're currently hard-coding the version of GCC that exists at the time you installed imake: https://github.com/Homebrew/homebrew-x11/blob/master/imake.rb#L31-L33

So currently this means you have to reinstall imake whenever you upgrade GCC. There should be a better way to do this.

**Comment by shaomeng** [comment]
Gcc was installed on my system as a dependency required by imake. There was no gcc in any version in my system previously. It could be that gcc5.2 reporting itself 5.1?

**Comment by mistydemeo** [comment]
Fix in #111; will merge when it's ready.

**Comment by dunn** [comment]
Thanks Misty!

**Comment by DomT4** [comment]
Heh, was just about to look at this. Thanks Misty :bow:

**Comment by mistydemeo** [comment]
Should be fixed; can you upgrade imake and retry?

**Comment by shaomeng** [comment]
It works great right now! Thanks for the fix!
