### ISSUE TITLE
meld segfault on yosemite (10.10.4)

### ISSUE THREAD

**Issue by jon-ga** [Homebrew/homebrew-x11#114]
Related to https://github.com/Homebrew/homebrew/issues/36980, I see the following after running meld

    Couldn't bind the translation domain. Some translations won't work.
    'module' object has no attribute 'bindtextdomain'
    2015-07-30 10:48:48.193 Python[28065:262485] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.

And then when I close meld, python crashes.

    Segmentation fault: 11

The problem report states:

    Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
    Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

I installed meld by:

    brew tap homebrew/x11
    brew install meld

Interestingly enough, this is 100% reproducible by clicking the red "x" on the window, but if I use CMD-Q, there is no segfault.

**Comment by tschoonj** [comment]
Looks like an upstream issue.

Could you file a bug over this at [Gnome bugzilla](https://bugzilla.gnome.org/enter_bug.cgi?product=meld)?

Thanks

**Comment by bprodoehl** [comment]
I've been seeing this problem since moving to the 10.11 beta in July, and I see the same thing just running upstream meld (with homebrew's libgtk).  I finally posted my output and stack trace to this bug: https://bugzilla.gnome.org/show_bug.cgi?id=756225

**Comment by dabeale** [comment]
I had the same issue and a similar stack trace to bprodoehl. Running `brew reinstall gtk+3 --with-quartz-relocation` fixed the problem.

**Comment by bprodoehl** [comment]
Works! Fixes file diffs. Still get a segfault on close (if I click the red X), but this is a major improvement.

**Comment by dabeale** [comment]
The delete-event segfault may be something that should be passed up to the creators of meld. A simple way of solving it is to patch meldwindow.py. Add `import sys` to the top, and then `sys.exit(1)` to the end of `on_delete_event` at about line 303, it will remove the segfault, although the memory may not be properly cleaned.

**Comment by SylvainCorlay** [comment]
@dabeale this solved the issue for me. Thanks. Do you think this is an upstream issue with meld and that they should make that change in the main repo?

**Comment by dabeale** [comment]
Yes. There is always the possibility that if you issue a patch it will not be fixed. Since the leak is only caused on exit of the main window it could be worse. It may also be a bug in pygobject, or gtk.

**Comment by DomT4** [comment]
Looks like this is the same issue as https://github.com/Homebrew/homebrew/issues/44722.

**Comment by SylvainCorlay** [comment]
As far as I am concerned, this issue is not fixed. Although the manual change in meld's source by @dabeale fixes the issue.

Could this issue be reopened?

**Comment by tschoonj** [comment]
Fixed in meld 3.14.2 (#162)
