### ISSUE TITLE
initialising terminator asks for python libvte

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-x11#115]
_From @aidylewis on August 3, 2015 9:10_

After brew installing terminator (homebrew/x11/terminator-0.97) and attempting to run it, I receive a message box that informs me I need to install libvte. However, vte is already installed through homebrew. 

```sh
$ ~ brew install vte
Warning: vte-0.28.2 already installed
```

```sh
$ ~ brew -v
Homebrew 0.9.5
```

```sh
$ ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F34
```

_Copied from original issue: Homebrew/homebrew#42399_

**Comment by DomT4** [comment]
@aidylewis What was the actual error you saw?

I get a bunch of warnings, but nothing related to `vte`:

```
ConfigBase::load: Unable to open /Users/Dominyk/.config/terminator/config ([Errno 2] No such file or directory: '/Users/Dominyk/.config/terminator/config')
Warning: python-keybinder is not installed. This means the hide_window shortcut will be unavailable
/usr/local/lib/python2.7/site-packages/terminatorlib/window.py:63: Warning: The property GtkWindow:allow-shrink is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.set_property('allow-shrink', True)
Unable to bind hide_window key, another instance/window has it.
ActivityWatch plugin unavailable: please install python-notify
PluginRegistry::load_plugins: Importing plugin activitywatch.py failed: 'module' object has no attribute 'AVAILABLE'
<Window object at 0x111019320 (terminatorlib+window+Window at 0x7fcf0d033050)> is not in registered window list
```

**Comment by aidylewis** [comment]
Hi @DomT4 

This is the stack trace the appears in addition to the messsge box.
```
ConfigBase::load: Unable to open /Users/lewisa29/.config/terminator/config ([Errno 2] No such file or directory: '/Users/lewisa29/.config/terminator/config')
Warning: python-keybinder is not installed. This means the hide_window shortcut will be unavailable
/usr/local/lib/python2.7/site-packages/terminatorlib/window.py:63: Warning: The property GtkWindow:allow-shrink is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.set_property('allow-shrink', True)
Unable to bind hide_window key, another instance/window has it.
```

**Comment by DomT4** [comment]
Not much different about out printouts there. I get no message box, It opens Terminator okay. When does the message box pop up for you?

**Comment by aidylewis** [comment]
You get terminator? It must have something do with the versions of python we are both using, but I am on 2.7.10. What version of python are you using? The message box appears after I type 'terminator'

**Comment by DomT4** [comment]
`Python 2.7.10` as well. Can you screenshot the message box or anything?

**Comment by aidylewis** [comment]
![screen shot 2015-08-05 at 10 07 24](https://cloud.githubusercontent.com/assets/6703997/9082158/f769a38e-3b59-11e5-93c7-5c8c292a0294.png)

**Comment by DomT4** [comment]
Hmm. Let's try the obvious solution first: `brew update && brew reinstall vte`

**Comment by aidylewis** [comment]
Hi @DomT4 

I removed all my Homebrew packages and uninstalled Homebrew. Re-installed Hombrew and  brew installed terminator. Terminator now opens. 

Thanks for your effort and sorry for wasting your time.

**Comment by DomT4** [comment]
Ah, quirky. It's possible that some local configuration error that we weren't able to detect was the root cause. Glad it's working as expected now! Don't worry at all, always happy to try and help.
