### ISSUE TITLE
gaf tool missing

### ISSUE THREAD

**Issue by jbattat** [Homebrew/homebrew-x11#122]
I don't see the gaf command-line tool in the geda-gaf installation.  For example, to make PDF of a schematic, you should be able to run:

```
gaf export -o filename.pdf filename.sch 
```

This utility is available in the geda-gaf git, but not in the homebrew version.  Could you add gaf to the homebrew version (apologies if it's there but I'm not seeing it)?

Also, `brew search geda` lists two versions.  I'm using homebrew/x11, is one preferred over the other?
```
$ brew search geda
geda-gaf	       homebrew/x11/geda-gaf
```

**Comment by dunn** [comment]
We'd be happy to get a PR to install `gaf` correctly!

Re: your two versions, geda-gaf was moved out of core into the X11 tap way back in 43882a26b5f15da065ccb32dac0b78622ba026e1; might want to run `brew update`.

**Comment by jbattat** [comment]
That's outside of my wheelhouse for now...

Also, I did `brew update` minutes before `brew search geda` and still see two versions.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
