### ISSUE TITLE
i3 dyld issues

### ISSUE THREAD

**Issue by clarkadamp** [Homebrew/homebrew-x11#124]
fresh install give the following:
dyld: lazy symbol binding failed: Symbol not found: _cairo_xcb_surface_create
  Referenced from: /usr/local/bin/i3
  Expected in: /usr/local/lib/libcairo.2.dylib

dyld: Symbol not found: _cairo_xcb_surface_create
  Referenced from: /usr/local/bin/i3
  Expected in: /usr/local/lib/libcairo.2.dylib

**Comment by DomT4** [comment]
Will be fixed by https://github.com/Homebrew/homebrew-x11/commit/ff0bb78235eaad127b736489c5034d159cbede81. Make sure you `brew update` and then `brew upgrade i3` should sort it out.
