### ISSUE TITLE
SWI-Prolog -- why here?

### ISSUE THREAD

**Issue by cbarrick** [Homebrew/homebrew-x11#125]
SWI-Prolog only depends on X11 if built `--with-xpce`, which is not the default. As a programming language interpreter, it is not inherently graphical, and other Prolog implementations live in the main repository (gnu-prolog, yap, mercury). SWI is very popular among Prolog implementations, certainly more so than gnu-prolog and yap, and is often used in university courses on logic programming.

What are your feelings towards moving the `swi-prolog` formula into the main repository?

**Comment by DomT4** [comment]
I presume when @mikemcquaid moved them he did something like a grep/ack/etc for files which had lines reading simply `depends_on :x11` without any optional flag to that and that possibly highlighted a couple of niche cases with that line inside `if build.with?` blocks outside of `def install`.

I'm not particularly opposed to moving it back if Mike doesn't mind.

**Comment by mikemcquaid** [comment]
If it's not the default we can move it back, yep.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by MikeMcQuaid** [comment]
Sorry, actually, this was migrated in https://github.com/Homebrew/homebrew-x11/pull/204.
