### ISSUE TITLE
Newer version of gtksourceviewmm3 needed after gtksourceview3 upgrade

### ISSUE THREAD

**Issue by eidheim** [Homebrew/homebrew-x11#131]
Gtksourceviewmm3 3.12 is not completely compatible with gtksourceview3 3.18. I'm getting assertion warnings on completion context. Seems like gtksourceviewmm3 unref the context object. Might be other issues also with using an older version with gtksourviewmm3 together with newer versions of gtksourceview3.

Thank you for Homebrew by the way!

**Comment by DomT4** [comment]
Track #130. Once that has been merged (It's waiting on https://github.com/Homebrew/homebrew/pull/44235) full compatibility should be restored.

**Comment by eidheim** [comment]
Thank you!
