### ISSUE TITLE
Scantailor, Build error on Mac OS X 10.11.1

### ISSUE THREAD

**Issue by davidbecher** [Homebrew/homebrew-x11#157]
Hey,

I just tried to install scantailor via homebrew but it just won't work. Here some output of the terminal:

```
==> cmake . -DPNG_INCLUDE_DIR=/opt/X11/include -DCMAKE_CXX_FLAGS=-std=c++11 -std
==> make install
Last 15 lines from /Users/dbecher/Library/Logs/Homebrew/scantailor/02.make:
[ 48%] Building CXX object CMakeFiles/stcore.dir/OutputFileNameGenerator.cpp.o
/usr/local/Library/ENV/4.3/clang++   -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_TEST_DYN_LINK -D_BIND_TO_CURRENT_VCLIBS_VERSION=1 -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/. -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/foundation -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/math -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/interaction -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/zones -I/usr/local/include -I/opt/X11/include -I/usr/local/Cellar/qt/4.8.7_1/include/QtDesigner -I/usr/local/Cellar/qt/4.8.7_1/include/QtDeclarative -I/usr/local/Cellar/qt/4.8.7_1/include/QtScriptTools -I/usr/local/Cellar/qt/4.8.7_1/include/QtXml -I/usr/local/Cellar/qt/4.8.7_1/include/QtSql -I/usr/local/Cellar/qt/4.8.7_1/include/QtOpenGL -I/usr/local/Cellar/qt/4.8.7_1/include/QtMultimedia -I/usr/local/Cellar/qt/4.8.7_1/include/QtNetwork -I/usr/local/Cellar/qt/4.8.7_1/include/phonon -I/usr/local/Cellar/qt/4.8.7_1/include/QtXmlPatterns -I/usr/local/Cellar/qt/4.8.7_1/include/QtWebKit -I/usr/local/Cellar/qt/4.8.7_1/include/QtHelp -I/usr/local/Cellar/qt/4.8.7_1/include/QtUiTools -I/usr/local/Cellar/qt/4.8.7_1/include/QtTest -I/usr/local/Cellar/qt/4.8.7_1/include/QtScript -I/usr/local/Cellar/qt/4.8.7_1/include/QtSvg -I/usr/local/Cellar/qt/4.8.7_1/include/QtGui -I/usr/local/Cellar/qt/4.8.7_1/lib/QtCore.framework/Headers -I/usr/local/Cellar/qt/4.8.7_1/mkspecs/default -I/usr/local/Cellar/qt/4.8.7_1/include -F/usr/local/Cellar/qt/4.8.7_1/lib -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1  -std=c++11 -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -o CMakeFiles/stcore.dir/OutputFileNameGenerator.cpp.o -c /tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/OutputFileNameGenerator.cpp
[ 49%] Building CXX object CMakeFiles/stcore.dir/PageRange.cpp.o
/usr/local/Library/ENV/4.3/clang++   -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_TEST_DYN_LINK -D_BIND_TO_CURRENT_VCLIBS_VERSION=1 -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/. -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/foundation -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/math -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/interaction -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/zones -I/usr/local/include -I/opt/X11/include -I/usr/local/Cellar/qt/4.8.7_1/include/QtDesigner -I/usr/local/Cellar/qt/4.8.7_1/include/QtDeclarative -I/usr/local/Cellar/qt/4.8.7_1/include/QtScriptTools -I/usr/local/Cellar/qt/4.8.7_1/include/QtXml -I/usr/local/Cellar/qt/4.8.7_1/include/QtSql -I/usr/local/Cellar/qt/4.8.7_1/include/QtOpenGL -I/usr/local/Cellar/qt/4.8.7_1/include/QtMultimedia -I/usr/local/Cellar/qt/4.8.7_1/include/QtNetwork -I/usr/local/Cellar/qt/4.8.7_1/include/phonon -I/usr/local/Cellar/qt/4.8.7_1/include/QtXmlPatterns -I/usr/local/Cellar/qt/4.8.7_1/include/QtWebKit -I/usr/local/Cellar/qt/4.8.7_1/include/QtHelp -I/usr/local/Cellar/qt/4.8.7_1/include/QtUiTools -I/usr/local/Cellar/qt/4.8.7_1/include/QtTest -I/usr/local/Cellar/qt/4.8.7_1/include/QtScript -I/usr/local/Cellar/qt/4.8.7_1/include/QtSvg -I/usr/local/Cellar/qt/4.8.7_1/include/QtGui -I/usr/local/Cellar/qt/4.8.7_1/lib/QtCore.framework/Headers -I/usr/local/Cellar/qt/4.8.7_1/mkspecs/default -I/usr/local/Cellar/qt/4.8.7_1/include -F/usr/local/Cellar/qt/4.8.7_1/lib -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1  -std=c++11 -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -o CMakeFiles/stcore.dir/PageRange.cpp.o -c /tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/PageRange.cpp
[ 49%] Building CXX object CMakeFiles/stcore.dir/SelectedPage.cpp.o
/usr/local/Library/ENV/4.3/clang++   -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_TEST_DYN_LINK -D_BIND_TO_CURRENT_VCLIBS_VERSION=1 -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/. -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/foundation -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/math -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/interaction -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/zones -I/usr/local/include -I/opt/X11/include -I/usr/local/Cellar/qt/4.8.7_1/include/QtDesigner -I/usr/local/Cellar/qt/4.8.7_1/include/QtDeclarative -I/usr/local/Cellar/qt/4.8.7_1/include/QtScriptTools -I/usr/local/Cellar/qt/4.8.7_1/include/QtXml -I/usr/local/Cellar/qt/4.8.7_1/include/QtSql -I/usr/local/Cellar/qt/4.8.7_1/include/QtOpenGL -I/usr/local/Cellar/qt/4.8.7_1/include/QtMultimedia -I/usr/local/Cellar/qt/4.8.7_1/include/QtNetwork -I/usr/local/Cellar/qt/4.8.7_1/include/phonon -I/usr/local/Cellar/qt/4.8.7_1/include/QtXmlPatterns -I/usr/local/Cellar/qt/4.8.7_1/include/QtWebKit -I/usr/local/Cellar/qt/4.8.7_1/include/QtHelp -I/usr/local/Cellar/qt/4.8.7_1/include/QtUiTools -I/usr/local/Cellar/qt/4.8.7_1/include/QtTest -I/usr/local/Cellar/qt/4.8.7_1/include/QtScript -I/usr/local/Cellar/qt/4.8.7_1/include/QtSvg -I/usr/local/Cellar/qt/4.8.7_1/include/QtGui -I/usr/local/Cellar/qt/4.8.7_1/lib/QtCore.framework/Headers -I/usr/local/Cellar/qt/4.8.7_1/mkspecs/default -I/usr/local/Cellar/qt/4.8.7_1/include -F/usr/local/Cellar/qt/4.8.7_1/lib -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1  -std=c++11 -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -o CMakeFiles/stcore.dir/SelectedPage.cpp.o -c /tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/SelectedPage.cpp
[ 49%] Building CXX object CMakeFiles/stcore.dir/Utils.cpp.o
/usr/local/Library/ENV/4.3/clang++   -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_TEST_DYN_LINK -D_BIND_TO_CURRENT_VCLIBS_VERSION=1 -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/. -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/foundation -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/math -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/interaction -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/zones -I/usr/local/include -I/opt/X11/include -I/usr/local/Cellar/qt/4.8.7_1/include/QtDesigner -I/usr/local/Cellar/qt/4.8.7_1/include/QtDeclarative -I/usr/local/Cellar/qt/4.8.7_1/include/QtScriptTools -I/usr/local/Cellar/qt/4.8.7_1/include/QtXml -I/usr/local/Cellar/qt/4.8.7_1/include/QtSql -I/usr/local/Cellar/qt/4.8.7_1/include/QtOpenGL -I/usr/local/Cellar/qt/4.8.7_1/include/QtMultimedia -I/usr/local/Cellar/qt/4.8.7_1/include/QtNetwork -I/usr/local/Cellar/qt/4.8.7_1/include/phonon -I/usr/local/Cellar/qt/4.8.7_1/include/QtXmlPatterns -I/usr/local/Cellar/qt/4.8.7_1/include/QtWebKit -I/usr/local/Cellar/qt/4.8.7_1/include/QtHelp -I/usr/local/Cellar/qt/4.8.7_1/include/QtUiTools -I/usr/local/Cellar/qt/4.8.7_1/include/QtTest -I/usr/local/Cellar/qt/4.8.7_1/include/QtScript -I/usr/local/Cellar/qt/4.8.7_1/include/QtSvg -I/usr/local/Cellar/qt/4.8.7_1/include/QtGui -I/usr/local/Cellar/qt/4.8.7_1/lib/QtCore.framework/Headers -I/usr/local/Cellar/qt/4.8.7_1/mkspecs/default -I/usr/local/Cellar/qt/4.8.7_1/include -F/usr/local/Cellar/qt/4.8.7_1/lib -I/tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1  -std=c++11 -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -o CMakeFiles/stcore.dir/Utils.cpp.o -c /tmp/scantailor20151120-44367-1g3dxco/scantailor-0.9.11.1/Utils.cpp
[ 49%] Linking CXX static library libstcore.a
/usr/local/Cellar/cmake/3.4.0/bin/cmake -P CMakeFiles/stcore.dir/cmake_clean_target.cmake
/usr/local/Cellar/cmake/3.4.0/bin/cmake -E cmake_link_script CMakeFiles/stcore.dir/link.txt --verbose=1
/usr/bin/ar qc libstcore.a  CMakeFiles/stcore.dir/BackgroundExecutor.cpp.o CMakeFiles/stcore.dir/OpenGLSupport.cpp.o CMakeFiles/stcore.dir/PixmapRenderer.cpp.o CMakeFiles/stcore.dir/BubbleAnimation.cpp.o CMakeFiles/stcore.dir/ProcessingIndicationWidget.cpp.o CMakeFiles/stcore.dir/NonOwningWidget.cpp.o CMakeFiles/stcore.dir/Dpi.cpp.o CMakeFiles/stcore.dir/Dpm.cpp.o CMakeFiles/stcore.dir/SmartFilenameOrdering.cpp.o CMakeFiles/stcore.dir/RelinkablePath.cpp.o CMakeFiles/stcore.dir/ImageInfo.cpp.o CMakeFiles/stcore.dir/ImageFileInfo.cpp.o CMakeFiles/stcore.dir/ImageMetadata.cpp.o CMakeFiles/stcore.dir/RecentProjects.cpp.o CMakeFiles/stcore.dir/OutOfMemoryHandler.cpp.o CMakeFiles/stcore.dir/CommandLine.cpp.o CMakeFiles/stcore.dir/PageSelectionAccessor.cpp.o CMakeFiles/stcore.dir/ContentSpanFinder.cpp.o CMakeFiles/stcore.dir/PhysicalTransformation.cpp.o CMakeFiles/stcore.dir/ImageTransformation.cpp.o CMakeFiles/stcore.dir/ImageViewBase.cpp.o CMakeFiles/stcore.dir/BasicImageView.cpp.o CMakeFiles/stcore.dir/StageListView.cpp.o CMakeFiles/stcore.dir/DebugImageView.cpp.o CMakeFiles/stcore.dir/TabbedDebugImages.cpp.o CMakeFiles/stcore.dir/ThumbnailPixmapCache.cpp.o CMakeFiles/stcore.dir/ThumbnailBase.cpp.o CMakeFiles/stcore.dir/ThumbnailFactory.cpp.o CMakeFiles/stcore.dir/IncompleteThumbnail.cpp.o CMakeFiles/stcore.dir/ContentBoxPropagator.cpp.o CMakeFiles/stcore.dir/PageOrientationPropagator.cpp.o CMakeFiles/stcore.dir/DebugImages.cpp.o CMakeFiles/stcore.dir/ImageId.cpp.o CMakeFiles/stcore.dir/PageId.cpp.o CMakeFiles/stcore.dir/PageInfo.cpp.o CMakeFiles/stcore.dir/BackgroundTask.cpp.o CMakeFiles/stcore.dir/ProcessingTaskQueue.cpp.o CMakeFiles/stcore.dir/PageSequence.cpp.o CMakeFiles/stcore.dir/StageSequence.cpp.o CMakeFiles/stcore.dir/ProjectPages.cpp.o CMakeFiles/stcore.dir/FilterData.cpp.o CMakeFiles/stcore.dir/ImageMetadataLoader.cpp.o CMakeFiles/stcore.dir/TiffReader.cpp.o CMakeFiles/stcore.dir/TiffWriter.cpp.o CMakeFiles/stcore.dir/PngMetadataLoader.cpp.o CMakeFiles/stcore.dir/TiffMetadataLoader.cpp.o CMakeFiles/stcore.dir/JpegMetadataLoader.cpp.o CMakeFiles/stcore.dir/ImageLoader.cpp.o CMakeFiles/stcore.dir/ErrorWidget.cpp.o CMakeFiles/stcore.dir/OrthogonalRotation.cpp.o CMakeFiles/stcore.dir/WorkerThread.cpp.o CMakeFiles/stcore.dir/LoadFileTask.cpp.o CMakeFiles/stcore.dir/FilterOptionsWidget.cpp.o CMakeFiles/stcore.dir/ProjectReader.cpp.o CMakeFiles/stcore.dir/ProjectWriter.cpp.o CMakeFiles/stcore.dir/XmlMarshaller.cpp.o CMakeFiles/stcore.dir/XmlUnmarshaller.cpp.o CMakeFiles/stcore.dir/AtomicFileOverwriter.cpp.o CMakeFiles/stcore.dir/EstimateBackground.cpp.o CMakeFiles/stcore.dir/Despeckle.cpp.o CMakeFiles/stcore.dir/ThreadPriority.cpp.o CMakeFiles/stcore.dir/FileNameDisambiguator.cpp.o CMakeFiles/stcore.dir/OutputFileNameGenerator.cpp.o CMakeFiles/stcore.dir/PageRange.cpp.o CMakeFiles/stcore.dir/SelectedPage.cpp.o CMakeFiles/stcore.dir/Utils.cpp.o
/usr/bin/ranlib libstcore.a
[ 49%] Built target stcore
make: *** [all] Error 2
```

**Comment by dunn** [comment]
Sorry for the delay! Can you post the full `brew gist-logs scantailor`? Thanks!

**Comment by davidbecher** [comment]
Here you go :)

https://gist.github.com/anonymous/176b8461b298b97fb296

**Comment by dunn** [comment]
OK, I see the same error.  I wonder if it's not compatible with Boost 1.59?

**Comment by dunn** [comment]
If you're up for it, attempting a build outside of Homebrew would help us figure out if it's an upstream issue or not.

**Comment by atomotic** [comment]
i got errors too (on a fresh elcap) https://gist.github.com/atomotic/3e78b7b8e962838774eb  
do you suggest to try a manual compilation outside brew, but using patches or trying gcc instead of clang?

**Comment by dunn** [comment]
If you get a different result outside of Homebrew, or with GCC within Homebrew, that will be useful information.

**Comment by atomotic** [comment]
tried with gcc

	brew install gcc
	export CC=gcc-5
	export CXX=g++-5
	export CPP=cpp-5
	export LD=gcc-5	
	
then applied this [patch](https://gist.githubusercontent.com/jkseppan/ccf72d14f8b0efee6c7d/raw/dc97fbeb6b086a44c75b857a0f31e7a4f2adcdda/scantailor-0.9.11.1-moc-boost.patch) to [scantailor 0.9.11](https://downloads.sourceforge.net/project/scantailor/scantailor/0.9.11.1/scantailor-0.9.11.1.tar.gz)

build fails:	
	
	
	➜  scantailor-0.9.11.1  make
	[  3%] Built target compile_translations
	[  6%] Built target toplevel_ui_sources
	[  7%] Generating PictureZoneEditor.h.moc
	[  7%] Generating FillZoneEditor.h.moc
	[  7%] Generating DespeckleView.h.moc
	[  7%] Generating DewarpingView.h.moc
	[  8%] Generating ChangeDewarpingDialog.h.moc
	[  8%] Generating ui_OutputApplyColorsDialog.h
	[  8%] Generating ui_OutputChangeDewarpingDialog.h
	[  8%] Generating ui_OutputChangeDpiDialog.h
	[  9%] Generating ui_OutputOptionsWidget.h
	Scanning dependencies of target output
	[  9%] Building CXX object filters/output/CMakeFiles/output.dir/ApplyColorsDialog.cpp.o
	[  9%] Building CXX object filters/output/CMakeFiles/output.dir/ChangeDpiDialog.cpp.o
	[  9%] Building CXX object filters/output/CMakeFiles/output.dir/ImageView.cpp.o
	[ 10%] Building CXX object filters/output/CMakeFiles/output.dir/TabbedImageView.cpp.o
	[ 10%] Building CXX object filters/output/CMakeFiles/output.dir/Filter.cpp.o
	/tmp/scantailor-0.9.11.1/filters/output/Filter.cpp: In member function 'virtual QDomElement output::Filter::saveSettings(const ProjectWriter&, QDomDocument&) const':
	/tmp/scantailor-0.9.11.1/filters/output/Filter.cpp:100:43: error: reference to '_1' is ambiguous
	    this, boost::ref(doc), var(filter_el), _1, _2
	                                           ^
	In file included from /usr/local/include/boost/lambda/lambda.hpp:14:0,
	                 from /tmp/scantailor-0.9.11.1/filters/output/Filter.cpp:31:
	/usr/local/include/boost/lambda/core.hpp:69:37: note: candidates are: boost::lambda::placeholder1_type& boost::lambda::{anonymous}::_1
	   boost::lambda::placeholder1_type& _1 = free1;
	                                     ^
	In file included from /usr/local/include/boost/bind/bind.hpp:2032:0,
	                 from /usr/local/include/boost/bind.hpp:22,
	                 from /usr/local/include/boost/multi_index/sequenced_index.hpp:17,
	                 from /tmp/scantailor-0.9.11.1/./ProjectWriter.h:33,
	                 from /tmp/scantailor-0.9.11.1/filters/output/Filter.cpp:28:
	/usr/local/include/boost/bind/placeholders.hpp:55:15: note:                 boost::arg<1> {anonymous}::_1
	 boost::arg<1> _1;
	               ^
	/tmp/scantailor-0.9.11.1/filters/output/Filter.cpp:100:47: error: reference to '_2' is ambiguous
	    this, boost::ref(doc), var(filter_el), _1, _2
	                                               ^
	In file included from /usr/local/include/boost/lambda/lambda.hpp:14:0,
	                 from /tmp/scantailor-0.9.11.1/filters/output/Filter.cpp:31:
	/usr/local/include/boost/lambda/core.hpp:70:37: note: candidates are: boost::lambda::placeholder2_type& boost::lambda::{anonymous}::_2
	   boost::lambda::placeholder2_type& _2 = free2;
	                                     ^
	In file included from /usr/local/include/boost/bind/bind.hpp:2032:0,
	                 from /usr/local/include/boost/bind.hpp:22,
	                 from /usr/local/include/boost/multi_index/sequenced_index.hpp:17,
	                 from /tmp/scantailor-0.9.11.1/./ProjectWriter.h:33,
	                 from /tmp/scantailor-0.9.11.1/filters/output/Filter.cpp:28:
	/usr/local/include/boost/bind/placeholders.hpp:56:15: note:                 boost::arg<2> {anonymous}::_2
	 boost::arg<2> _2;
	               ^
	make[2]: *** [filters/output/CMakeFiles/output.dir/Filter.cpp.o] Error 1
	make[1]: *** [filters/output/CMakeFiles/output.dir/all] Error 2
	make: *** [all] Error 2

**Comment by atomotic** [comment]
saw this [message](http://www.diybookscanner.org/forum/viewtopic.php?f=21&t=3259&sid=78b9355e91fb30a8a44f32fc0223fc09#p19623) on diybookscanner forum, suggesting:

	It's this old issue except with newer versions of boost it seems to happen even if you are careful
     not to include <boost/bind.hpp> and <boost/lambda/lambda.hpp> into the same .cpp file. 
     The following procedure may help (untested):

	In source code, find all files containing "#include <boost/lambda/lambda.hpp>". 
        In those files only, make the following changes:
	_1 => boost::lambda::_1
	_2 => boost::lambda::_2
	...
	_9 => boost::lambda::_9

**Comment by artelse** [comment]
Having the same error, I tried the above suggestion. Find in files:

` $ grep -r -l "#include <boost/lambda/lambda.hpp>" /usr/local/Cellar/boost/1.59.0/include/boost/ `

`/usr/local/Cellar/boost/1.59.0/include/boost//bimap/support/lambda.hpp`
`/usr/local/Cellar/boost/1.59.0/include/boost//units/lambda.hpp`

The first file does contain the exact `boost::lambda::_1` so no need to change. The other file had none. So basically for version 1.59.0 there is nothing to change? Are there other suggestions on how to fix the `[ 49%] Built target stcore
make: *** [all] Error 2` ?

**Comment by reboot81** [comment]
Having the same error as @artelse with 10.11.2 & Boost 1.60.0_1

**Comment by ilovezfs** [comment]
`git bisect` shows that this is a regression introduced by
https://github.com/Homebrew/homebrew-core/commit/fbfc9d6b71b8dfc757ac31f0b866cab7dda2675a

So one option would be to vendor in boost 1.58.0

**Comment by ilovezfs** [comment]
```brew pull https://github.com/Homebrew/homebrew-x11/pull/197``` if you'd like to try the fix.
https://github.com/Homebrew/homebrew-x11/pull/197

**Comment by atomotic** [comment]
great, successfully compiled, thanks.

worth to mention that the original scantailor author is working on this:
https://github.com/Tulon/scantailor (experimental branch)
here the announce on the forum:
http://www.diybookscanner.org/forum/viewtopic.php?f=21&t=3195

a lot of improvements, like opencl support. even this experimental branch has some compilation troubles on osx, see last messages on the forum thread

**Comment by ilovezfs** [comment]
@atomotic OK, I got the newest :devel and :head building now: https://github.com/Homebrew/homebrew-x11/pull/197

**Comment by MikeMcQuaid** [comment]
Presumed fixed by https://github.com/Homebrew/homebrew-x11/pull/205.
