### ISSUE TITLE
ddd failed to build on 10.11.1

### ISSUE THREAD

**Issue by ftram** [Homebrew/homebrew-x11#158]
While building ddd on OS X 10.11 (in the make phase) the following messages are showed: 
    gzip -c -9 ddd.info.txt > ddd.info.txt.gz~ && mv ddd.info.txt.gz~ ddd.info.txt.gz
    gzip: can't stat: gzip (gzip): No such file or directory
    make[2]: *** [ddd.info.txt.gz] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [all] Error 2
    make: *** [all-recursive] Error 1
Then some information messages are showed and finally the error messages:
    Error: homebrew/x11/ddd 3.3.12 did not build

Here the Gist I have uploaded https://gist.github.com/a06a8586c32073a4706a

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
