### ISSUE TITLE
failure configuring imake on Mavericks

### ISSUE THREAD

**Issue by thomasgi** [Homebrew/homebrew-x11#16]
When installing imake 1.0.7 the configure process fails with following message:

==> ./configure --prefix=/usr/local/Cellar/imake/1.0.7
checking for cpp... /usr/local/Library/ENV/4.3/cpp
checking if /usr/local/Library/ENV/4.3/cpp requires -undef... clang: error: no input files
clang: error: no input files
clang: error: no input files
configure: error: /usr/local/Library/ENV/4.3/cpp defines unix with or without -undef.  I don't know what to do.

GIST: https://gist.github.com/e3e1dfd90cea0f2bdc3c

**Comment by veprbl** [comment]
Do you still have this issue?

**Comment by thomasgi** [comment]
Yes, the issue is still present.

**Comment by veprbl** [comment]
There was an identical issue Homebrew/homebrew#34550 . I see that your ```brew doctor``` is good, but could you manually check that your Xcode, SDK's, Command Line Tools(if you have some) are up to date?

**Comment by odousse** [comment]
I opened Homebrew/homebrew#34550 originally, and interestingly, I am running into the same problem again on a different computer. It seems that after upgrading to Yosemite, things are broken somehow. Since there was no Xcode update available this time, I fixed it by installing the command line tools and pointing code-select at them. 
Hoping that this helps...

**Comment by veprbl** [comment]
I've modified #20 to fix your case.

Please see if
```
brew install https://raw.githubusercontent.com/veprbl/homebrew-x11/imake-fix/imake.rb
```
works for you.

**Comment by thomasgi** [comment]
Thanks for your effort. I will test it on Monday when I have access to the affected machine.

Am 31.01.2015 um 16:29 schrieb Dmitry Kalinkin <notifications@github.com>:

**Comment by thomasgi** [comment]
Yes, the new recipe works for me.

Thanks for your work.

Von:  Dmitry Kalinkin <notifications@github.com>
Antworten an:  Homebrew/homebrew-x11
<reply+00a082e4d643082730dd7ab8e77a72ff92df275ac37794d392cf0000000110e4b6c69
2a169ce033b6795@reply.github.com>
Datum:  Samstag, 31. Januar 2015 16:29
An:  Homebrew/homebrew-x11 <homebrew-x11@noreply.github.com>
Cc:  Thomas Gimpel <thomas.gimpel@innoventif.de>
Betreff:  Re: [homebrew-x11] failure configuring imake on Mavericks (#16)


I've modified #20 <https://github.com/Homebrew/homebrew-x11/pull/20>  to fix
your case.

Please see if
brew install 
https://raw.githubusercontent.com/veprbl/homebrew-x11/imake-fix/imake.rb
works for you.

‹
Reply to this email directly or view it on GitHub
<https://github.com/Homebrew/homebrew-x11/issues/16#issuecomment-72322060> .
