### ISSUE TITLE
rxvt-unicode - what can we do to enable Perl?

### ISSUE THREAD

**Issue by larryhynes** [Homebrew/homebrew-x11#163]
The formula for rxvt-unicode disables Perl support if clang is the compiler.

`args << "--disable-perl" if ENV.compiler == :clang`

It could be argued that one of rxvt-unicode's strengths is its Perl integration, which enables a number of features. (I'm thinking specifically about searchable scrollback.)

Is there anything that can be done to enable Perl support? In the first instance, is there anything that I can do locally to override clang and specify a different compiler for this formula? Failing that, or possibly in tandem with it, can the formula be revised to assist in enabling Perl integration?

I'm happy to help within my own limitations, please let me know how I can be of assistance.

**Comment by DomT4** [comment]
See https://github.com/Homebrew/homebrew/issues/27955. No idea if Perl ever fixed that bug. If they have, we may be able to review the line there.

**Comment by larryhynes** [comment]
Ah, I see - thanks. As per @mistydemeo in #27955, `brew tap homebrew/versions`, `brew install homebrew/versions/gcc49` and `brew install rxvt-unicode --cc=gcc-4.9` seems to have done the trick. (For the benefit of Future Me: you found the relevant gcc version in `man brew`, listed under `--cc`.)
