### ISSUE TITLE
graphicsmagick to be updated on homebrew/homebrew will require xastir to be rebuilt

### ISSUE THREAD

**Issue by carandraug** [Homebrew/homebrew-x11#165]
I have reported homebrew/homebrew#46101 about changing the default quantum-depth option of GraphicsMagick to 16 (see that for reasoning). I then made the pull request homebrew/homebrew#46248 with those changes where I was asked to ping homebrew/x11 since this may break xastir. That pull request has now been moved to homebrew/homebrew#47014

On a related note, I will point out that it is possible for users to change the default quantum depth. In such cases, formulas may have to figure out the options used to build  the dependencies and adapt to it. This is an existing problem, and not due to the change of default (see existing issue homebrew/homebrew-science#2737).

**Comment by carandraug** [comment]
For what is worth, Homebrew/homebrew#47014 got finally accepted. It is likely that xastir revision number should be bumped.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
