### ISSUE TITLE
i3 + XQuartz + (maybe) El Cap

### ISSUE THREAD

**Issue by bceverly** [Homebrew/homebrew-x11#170]
Hi,

I'm trying to get i3 running under XQuartz on my 13" retina Macbook Pro running 10.11.2 and the only last remaining issue is that I can't for the life of me get my meta key working.  I've tried every combination of the input preferences checkboxes on XQuartz, I've tried full screen and not full screen, I've tried using .Xmodmap to explicitly map Meta_R and Meta_L to mod1 and I'm stumped.

If anyone has this working and can share their .config/i3/config file, along with any other tweaks they had to do in .Xmodmap, .Xresources, or .xinitrc.d/* I would massively appreciate it.

Thanks.

**Comment by dunn** [comment]
If you could try installing i3 outside of Homebrew, that would help us confirm that this is a Homebrew-specific problem.  Thanks!

**Comment by bceverly** [comment]
Trying to build from source but bumping my head against the wall.  I have created a CPATH that pulls in the include files I need; however, now I'm hitting an undefined type of CARDINAL.  Any suggestions?  I searched for documentation on how to build / install on the Mac and outside of building from source, I came up dry.  Perhaps my Google-fu is weak...

**Comment by apjanke** [comment]
What key are you using for Meta? Option (aka "alt")? One or both sides? And what isn't working about it? From what I understand about XQuartz and Mac keyboards, you don't really have a Meta key, and should maybe be mapping Alt instead.

**Comment by afh** [comment]
@bceverly I have i3 (4.12 see #210) running on XQuartz (2.7.9) on Mac OS X El Capitan (10.11.4 (15E65)) and use both command keys (⌘) as a modifier.

Hope the following helps:

```
% grep 'set $mod' ~/.config/i3/config
set $mod Mod2
```

```
% xmodmap
xmodmap:  up to 2 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x40),  Shift_R (0x44)
lock        Caps_Lock (0x41)
control     Control_L (0x43),  Control_R (0x46)
mod1        Mode_switch (0x42),  Mode_switch (0x45)
mod2        Meta_L (0x3f),  Meta_R (0x47)
mod3      
mod4      
mod5      
```

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by Michael-Jing** [comment]
Could anyone share a step by step guide on how to set up i3 on mac osx? I like the i3 style very much, and I got a macbook pro recently, I have installed Ubuntu in order to use i3, but even though Ubuntu is good enough, the energy saving system is much better on osx.
