### ISSUE TITLE
Gobby 0.5 and OS X El Capitan: Library not loaded

### ISSUE THREAD

**Issue by aXon** [Homebrew/homebrew-x11#180]
The gobby bottle (https://github.com/Homebrew/homebrew-x11/blob/master/gobby.rb) does not seem to work with the latest gnutls package. Executing gobby-0.5 results in

> dyld: Library not loaded: /usr/local/lib/libgnutls.28.dylib
>   Referenced from: /usr/local/bin/gobby-0.5
>   Reason: image not found
> Trace/BPT trap: 5

I tried reinstalling gnutls and gobby, but the error persists.

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-x11/commit/5ea2f45c064535651fbbb6d55b1da21395596657. Thanks for the report!
