### ISSUE TITLE
rdesktop slow rendering since el capitan

### ISSUE THREAD

**Issue by 0bs3v3r** [Homebrew/homebrew-x11#184]
Hello,

Since el capitan it seems rdesktop is broken (slow rendering)
Have had no problems with yosemite.

Has anyone else noticed this?

Kind regards,
Bert

**Comment by apjanke** [comment]
This doesn't seem likely to be a Homebrew-specific issue. If you install rdesktop outside of Homebrew on El Cap, does it show similar performance problems?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
