### ISSUE TITLE
Select/copy text with mupdf

### ISSUE THREAD

**Issue by andrewsanchez** [Homebrew/homebrew-x11#206]
I apologize in advance if this is not the appropriate place to ask, but I was wondering if anybody has successfully been able to select and copy text using mupdf.  I obtained mupdf via `brew install homebrew/x11/mupdf`

I've tried right clicking to select/copy, and I've tried searching for a term to select a word, then using shift+left/right to select text and various other combinations, none of which worked.

**Comment by dunn** [comment]
If you can install mupdf outside of Homebrew that would help us determine if it's an upstream issue or not.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
