### ISSUE TITLE
freeglut not latest stable version

### ISSUE THREAD

**Issue by guygma** [Homebrew/homebrew-x11#214]
Version 3.0.0 appears to have been out since March 2015 and has also recently been updated as of Feb 2016. Is there a reason why this isn't the version included in the formula other than it just hasn't come up yet?

I am having issues with ipython --gui=glut requiring freeglut but not working with the 2.8 release currently installed by homebrew which is what lead me to this in the first place.

**Comment by DomT4** [comment]
Couldn't get it to build [personally](https://gist.github.com/anonymous/b702cd688411303fa0f4564b758eca54). More than happy to review a PR if you have better luck.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
