### ISSUE TITLE
macOS 10.12 Broken Formulae

### ISSUE THREAD

**Issue by theeternalsw0rd** [Homebrew/homebrew-x11#219]
This ties into the related issue on homebrew-core.

xdotool also has issues with the new time stuff like a number of packages there. This one is different though.

```
./osx_hacks.h:5:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')
typedef int clockid_t;
            ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:171:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.
```

Maybe the osx_hacks isn't necessary anymore. I'll take a look in the next day or two.

**Comment by theeternalsw0rd** [comment]
The osx_hacks is indeed no longer necessary. Patch at https://gist.githubusercontent.com/theeternalsw0rd/881fd3316f3858ff458c8d270a3c62bb/raw/cb108a790ae1af9f05a890fccd174075939fc30c/mac_sierra_xdotool.patch

**Comment by mistydemeo** [comment]
Reported upstream: https://github.com/jordansissel/xdotool/issues/138 Thank you!

**Comment by mistydemeo** [comment]
The new xdotool has a fix for this, and I've updated the formula.

**Comment by kdart** [comment]
FYI, ctorrent also has this problem.

> In file included from compat.c:11:
> ./compat.h:23:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')
> typedef int clockid_t;
>             ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:171:3: note: previous definition is here
> } clockid_t;
>   ^
> 1 error generated.
>

**Comment by mistydemeo** [comment]
Thanks! Do you mind reporting issues from the core repository in [its tracker](https://github.com/Homebrew/homebrew-core/issues/1957)?

Unfortunately ctorrent hasn't had any commits in its repo since around 2009, so this seems unlikely to get fixed.

**Comment by bikeNomad** [comment]
I'm trying to build xdotool, but am running into problems with its prerequisite of libxkbcommon:
```
libtool: link: rm -fr .libs/libxkbcommon.lax
libtool: link: ( cd ".libs" && rm -f "libxkbcommon.la" && ln -s "../libxkbcommon.la" "libxkbcommon.la" )
/bin/sh ./libtool  --tag=CC   --mode=link clang -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fvisibility=hidden -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wdocumentation -I/opt/X11/include -g -O2   -o libxkbcommon-x11.la -rpath /usr/local/Cellar/libxkbcommon/0.5.0/lib src/x11/libxkbcommon_x11_la-keymap.lo src/x11/libxkbcommon_x11_la-state.lo src/x11/libxkbcommon_x11_la-util.lo src/libxkbcommon_x11_la-context-priv.lo src/libxkbcommon_x11_la-keymap-priv.lo src/libxkbcommon_x11_la-atom.lo libxkbcommon.la -L/opt/X11/lib -lxcb -lxcb-xkb
libtool: link: clang -dynamiclib -Wl,-flat_namespace -Wl,-undefined -Wl,suppress -o .libs/libxkbcommon-x11.0.dylib  src/x11/.libs/libxkbcommon_x11_la-keymap.o src/x11/.libs/libxkbcommon_x11_la-state.o src/x11/.libs/libxkbcommon_x11_la-util.o src/.libs/libxkbcommon_x11_la-context-priv.o src/.libs/libxkbcommon_x11_la-keymap-priv.o src/.libs/libxkbcommon_x11_la-atom.o   ./.libs/libxkbcommon.dylib -L/opt/X11/lib -lxcb -lxcb-xkb  -O2   -install_name  /usr/local/Cellar/libxkbcommon/0.5.0/lib/libxkbcommon-x11.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
ld: file not found: @rpath/libclang_rt.asan_osx_dynamic.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libxkbcommon-x11.la] Error 1
make: *** [install] Error 2
```

**Comment by mistydemeo** [comment]
@bikeNomad Can you file a new issue for this, with the full [troubleshooting output](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md)? Thanks!

**Comment by MikeMcQuaid** [comment]
Note: this tap is being moved back into homebrew/core so anything that doesn't build when I do that will be removed.

**Comment by mockbutler** [comment]
@MikeMcQuaid Please don't delete it yet. I've forked the project from sourceforge.net to https://github.com/mockbutler/mtorrent and modified it so it now compiles on 10.12. Though it does now require CMake.

I am not at all familiar with writing/testing homebrew formulas, etc, but I was going to look at updating the this formula (or tap?). I'm not sure when you are moving the tap so I may not have a merge ready in time.

**Comment by MikeMcQuaid** [comment]
@mockbutler Unless you become the official upstream (i.e. blessed by the existing upstream) we would be deleting it anyway, sorry.

**Comment by MikeMcQuaid** [comment]
All formulae have (or will be very shortly) been deleted or migrated to other taps.
