### ISSUE TITLE
curlftpfs missing build requirements

### ISSUE THREAD

**Issue by theeternalsw0rd** [Homebrew/homebrew-x11#220]
For some reason, I needed all of these packages in order to build.
```libzzip libvorbis speex libshout sdl mariadb libmcrypt libgcrypt flac gobject-introspection guile autogen```

It's entirely possible my system was jacked up at the time. I had some issues with my installation, but in case anyone else has build issues complaining about lack of certain m4 files, this was the list of packages with the necessary files.

**Comment by ilovezfs** [comment]
what makes you think you needed those to build?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
