### ISSUE TITLE
grace exiting with SIGSYS

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/homebrew-x11#221]
_From @john139 on July 26, 2016 15:49_

### Bug reports:

Hello,
I used xmgrace which I successfully installed with homebrew (OS X 10.11.4), unfortunately I had to reinstall grace (with brew update and brew upgrade) and now I can't run it because the following error appears:

~$ xmgrace 
Warning: locale not supported by Xlib, locale set to C
Warning: Widget must be a VendorShell.
Warning: translation table syntax error: Unknown event type :   EnterWindow
Warning: ... found while parsing '<EnterWindow>:			ManagerEnter()'
Warning: String to TranslationTable conversion encountered errors

Oops! Got SIGSYS

Please use "Help/Comments" to report the bug.
Abort trap: 6

I have searched on the Internet, but the only place where this issue was discussed was here
https://github.com/Homebrew/legacy-homebrew/issues/27840#event-105239860, it was an optimisation problem. Could you please tell me if it is the same problem now or something else? 

_Copied from original issue: Homebrew/homebrew-core#3322_

**Comment by mistydemeo** [comment]
I can repro. I've tried it with both openmotif and lesstif, and rebuilt both from source. The formula already carries the workaround for the issue you noted above, so that seems to be unrelated.

**Comment by joanwa** [comment]
get same here: OS X 10.11.6, xquartz 2.7.9

**Comment by carbogno** [comment]
Same issue here:
OSX 10.11.6 (15G31)
XQuartz 2.7.9 (xorg-server 1.17.4)

**Comment by vegadj** [comment]
Same issue: 
OSX 10.11.6 
Xquartz 2.7.9 
grace 5.1.25_1
openmotif 2.3.4

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by Sunkworld** [comment]
Is there any temporary solution to this problem?

**Comment by mistydemeo** [comment]
Unfortunately I'm not aware of any.

**Comment by Sunkworld** [comment]
For example, manually build from other version of Xquartz, openmotif&grace?
I wish I hadn't erase my old laptop which has grace built on it...

**Comment by carbogno** [comment]
Does anyone have an idea what the cause is? Unfortunately, I have deleted my build history, but I suspect openmotif to be the culprit.

**Comment by Sunkworld** [comment]
It seems macport can install grace successfully...

**Comment by vegadj** [comment]
@Sunkworld 
Could you please share version details of dependency packages for grace that macport installed.
Maybe it can be useful for figuring out the issue in the brew.

**Comment by Sunkworld** [comment]
@vegadj 
openmotif 2.3.4
grace 5.1.25
and many other dependencies...

**Comment by Sunkworld** [comment]
@vegadj 
The following ports are dependencies of grace @5.1.25_1:
  openmotif
    pkgconfig
      libiconv
        gperf
    xbitmaps
    autoconf
      xz
        gettext
          expat
          ncurses
    automake
    libtool
    bison
      perl5
        perl5.22
          gdbm
      m4
      bison-runtime
    flex
    jpeg
    libpng
      zlib
    xorg-libsm
      xorg-xtrans
      xorg-libice
        xorg-xproto
    xorg-libXext
      xorg-util-macros
      xorg-libX11
        xorg-bigreqsproto
        xorg-xcmiscproto
        xorg-xextproto
        xorg-xf86bigfontproto
        xorg-inputproto
        xorg-libXdmcp
        xorg-libXau
        xorg-libxcb
          xorg-xcb-proto
            python27
              openssl
              sqlite3
                libedit
              db48
              bzip2
              python_select
              python2_select
            libxml2
          xorg-libpthread-stubs
        xorg-kbproto
    Xft2
      xrender
        xorg-renderproto
      freetype
      fontconfig
    xorg-libXmu
      xorg-libXt
    xorg-libXp
      xorg-printproto
  pdflib
  xpm
  openbrowser
    p5.22-mac-propertylist
      p5.22-xml-entities
        p5.22-html-parser
          p5.22-html-tagset
        p5.22-module-build
          p5.22-cpan-meta-yaml
          p5.22-parse-cpan-meta
          p5.22-cpan-meta
            p5.22-cpan-meta-requirements
            p5.22-scalar-list-utils
            p5.22-version
          p5.22-inc-latest
          p5.22-module-metadata
          p5.22-perl-ostype
          p5.22-podlators
            p5.22-pod-simple
              p5.22-pod-escapes

**Comment by haiboyu** [comment]
any update on this? thanks.

**Comment by apjanke** [comment]
I can also reproduce.

There is an upstream bug report for this: http://plasma-gate.weizmann.ac.il/Grace/phpbb/viewtopic.php?f=5&t=2799

And this looks like a corresponding discussion in MacPorts: https://trac.macports.org/ticket/45712?cversion=0&cnum_hist=16

It looks like it has to do with whether the Xm and Xt libraries are built with flat namespaces. The fix reported from MacPorts and the upstream Grace bug report require building Xt (and maybe others) with `-flat_namespace`. That's not an immediate option for Homebrew, since we don't build Xt; we just use the one shipped with Xquartz.

There's also this other Homebrew bug [here](https://github.com/Homebrew/legacy-homebrew/issues/27840), where a similar SIGSYS crash was fixed with `ENV.O1` to reduce the optimization. This may also be a regression on that: when I look at my build logs for `grace`, I see `clang` doing `-O2` instead of `-O1`.

```
clang -O2  -fno-common -Wall -Wpointer-arith -Wnested-externs -I.. -I.    -c -o airy.o airy.c
clang -O2  -fno-common -Wall -Wpointer-arith -Wnested-externs -I.. -I.    -c -o beta.o beta.c
clang -O2  -fno-common -Wall -Wpointer-arith -Wnested-externs -I.. -I.    -c -o chbevl.o chbevl.c
clang -O2  -fno-common -Wall -Wpointer-arith -Wnested-externs -I.. -I.    -c -o chdtr.o chdtr.c
```

**Comment by apjanke** [comment]
Oh, never mind on the `-O1` regression: I was looking at the pre-superenv logs.

**Comment by carbogno** [comment]
Following the advice in 
https://github.com/Homebrew/homebrew-x11/issues/255#issuecomment-255872671
I was able to resolve this issue.
