### ISSUE TITLE
mit-scheme does not work

### ISSUE THREAD

**Issue by Hardmath123** [Homebrew/homebrew-x11#24]
See homebrew/homebrew#33375 (fix in commit https://github.com/Homebrew/homebrew/commit/8c30f0bb124d5b5ecee132649b17b98df5cb4f79 but not in this repo), affects file https://github.com/homebrew/homebrew-x11/blob/master/mit-scheme.rb.

**Comment by DomT4** [comment]
Can you clarify? The `inreplace` fix you pointed to is included in the X11 formula here.

**Comment by Hardmath123** [comment]
Hmm… that's strange. I ran `brew update` and cleared the cache, but I still get the following error:
```
$ brew install mit-scheme
==> Installing mit-scheme from homebrew/homebrew-x11
==> Downloading http://ftpmirror.gnu.org/mit-scheme/stable.pkg/9.2/mit-scheme-c-9.2.tar.gz
######################################################################## 100.0%
Error: inreplace failed
lib/include/configure:
  expected replacement of "/usr/local" with #<Pathname:/…shortened…/homebrew/Cellar/mit-scheme/9.2>
```
(Yeah, my `brew` isn't in `/usr/local`, but that shouldn't be an issue?)

**Comment by DomT4** [comment]
It shouldn't be, but Ruby seems to think it is. Anything show up on `brew doctor`?

**Comment by Hardmath123** [comment]
Outdated XQuartz is the only thing that seems relevant, but I doubt this has anything to do with that.

**Comment by DomT4** [comment]
Would be surprised. What is your prefix? `brew config` will show it and a bunch of other details that could be useful. Is it a real prefix or a symlink elsewhere?

**Comment by Hardmath123** [comment]
```
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 1f2c60618edc2f947fbc2ca8d1f9378d2b428b2b
Last commit: 12 hours ago
HOMEBREW_PREFIX: [~]/my_bin/homebrew
HOMEBREW_CELLAR: [~]/my_bin/homebrew/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.9.5-x86_64
Xcode: 5.1.1
CLT: N/A
Clang: 5.1 build 503
X11: 2.7.6 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.7.0_75
```

**Comment by DomT4** [comment]
Does your Homebrew prefix actually have a tilde in the path or have you shortened that? @jacknagel Any known issues with underscores in the prefix path?

**Comment by Hardmath123** [comment]
It's a full `/Users/…` path, I redacted the login name when I pasted it.

**Comment by L2G** [comment]
I've been running into the same thing. I had to drop `lib/include/configure` from the list of files patched by `inreplace` to get anywhere building this.

**Comment by L2G** [comment]
I've attempted to whip this formula into better shape. See #84.

**Comment by ozeron** [comment]
Hello everyone!
I'm trying to install mit-scheme but I'm getting this error: 
```
==> etc/make-liarc.sh --disable-debug --prefix=/usr/local/Cellar/mit-scheme/9.2 --mandir=/usr/local/Cellar/mit-scheme/9.2/shar
checking size of uintptr_t... 0
checking size of intmax_t... 0
checking size of uintmax_t... 0
configure: error: SIZEOF_CHAR is not 1
configure: error: ./configure failed for microcode```

brew config
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 3feb508602a1caa0dd57092e27ef5968974a3538
Last commit: 30 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.10.3-x86_64
Xcode: N/A
CLT: 6.3.2.0.1.1431401888
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/ozeron/.rbenv/shims/ruby => /Users/ozeron/.rbenv/versions/2.2.2/bin/ruby
Java: N/A```

Can you help me to fix it, please!

**Comment by L2G** [comment]
@ozeron: See issue #84.

**Comment by ozeron** [comment]
@L2G I've just checked it out. I don't get what I should change, so I used a code from that commit in formula. I get same error `SIZEOF_CHAR is not 1` on `etc/make-liarc.sh`

**Comment by L2G** [comment]
@ozeron: What I meant to say is that I'm working on getting the mit-scheme formula to function properly, but it's not there yet; #84 shows the latest work that's been done.

**Comment by ozeron** [comment]
@l2g Oh... I'll keep my fingers crossed:)

**Comment by DomT4** [comment]
Should be resolved by https://github.com/Homebrew/homebrew-x11/commit/9506f453158cf28d45d40a537878a075670e8539.
