### ISSUE TITLE
xpenguins

### ISSUE THREAD

**Issue by nikolas** [Homebrew/homebrew-x11#246]
This would be a useful addition to this collection: http://xpenguins.seul.org/

I'll see if I can get this to build on my mac, unless someone else wants to try.

**Comment by tschoonj** [comment]
This hasn't seen a release since 2001 and looks highly unlikely to ever run on a Mac (and probably on any modern Linux distribution).

**Comment by ilovezfs** [comment]
Would be happy to look at a PR for this. :)

**Comment by nikolas** [comment]
It does in fact run on Ubuntu 16.04! I'll see what I can do.
