### ISSUE TITLE
TigerVNC 1.7.0 crashes on 64-bit OS X

### ISSUE THREAD

**Issue by zuxy** [Homebrew/homebrew-x11#254]
TigerVNC 1.7.0 introduces multithread decoding but its stack size exceeds the per-thread limit (512K) and leads to EXC_BADACCESS crash. Detailed discussion is at https://groups.google.com/forum/#!topic/tigervnc-users/NhVCQ3kRWpk

The attached diff fixes the problem.
[tiger-vnc.rb.txt](https://github.com/Homebrew/homebrew-x11/files/514436/tiger-vnc.rb.txt)

**Comment by fxcoudert** [comment]
Shouldn't this issue be closed, since the patch was merged in https://github.com/Homebrew/homebrew-x11/commit/6df9925d34bdf235f2a233563a2e684adc08d2a1 ?

**Comment by MikeMcQuaid** [comment]
Yes, thanks @fxcoudert.
