### ISSUE TITLE
Issue with pdf2svg: -lgdk_pixbuf-2.0 not found

### ISSUE THREAD

**Issue by MrBrezina** [Homebrew/homebrew-x11#27]
When trying to install pdf2svg, I get this:
```
ld: library not found for -lgdk_pixbuf-2.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [pdf2svg] Error 1
```

Here is the full report: https://gist.github.com/MrBrezina/861cfd8beecc0de12c38

Any ideas how to fix this? I am on Mac OS X 10.10.2 (14C109)

**Comment by DomT4** [comment]
Please provide the whole [Troubleshooting requested documentation](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting).

**Comment by MrBrezina** [comment]
Sorry, missed that. Here it is: https://gist.github.com/7da57dfceb79ccaf762b

**Comment by DomT4** [comment]
Thanks, Appreciated!

Curious this failure is; I can't reproduce it locally, and the only differences between our systems are Xcode and your Python installation into ` /Library `. Python seems to be have been called during the install process, which makes me wonder if that is the issue on this particular error. Thoughts @tdsmith?

**Comment by tdsmith** [comment]
Nah, red herring, I think. I've never seen that warning actually cause a problem; should probably remove it.

Does `/usr/local/Cellar/gdk-pixbuf/2.30.8/lib/libgdk_pixbuf-2.0.dylib` exist? Does `brew reinstall gdk-pixbuf` help?

**Comment by MrBrezina** [comment]
Tried ```brew reinstall```, that fixed gdk-pixbuf, but then there was similar problem with fontconfig. So, I tried to reinstall that too, and that fixed it. If I had to guess, I messed up the rights when moving machines.

Thank you!

**Comment by tdsmith** [comment]
You're welcome; glad to hear it!

**Comment by DomT4** [comment]
@tdsmith Thanks for sorting this! Appreciated.
