### ISSUE TITLE
openmotif install fails with failed patch

### ISSUE THREAD

**Issue by smalyshev** [Homebrew/homebrew-x11#283]
Get this when trying to install openmotif

```
==> Installing openmotif from homebrew/x11
==> Downloading https://downloads.sourceforge.net/project/motif/Motif%202.3.6%20Source%20Code/motif-2.3.6.tar.gz
Already downloaded: /Users/smalyshev/Library/Caches/Homebrew/openmotif-2.3.6.tar.gz
==> Patching
patching file configure.ac
patching file lib/Xm/XmP.h
patching file demos/programs/workspace/xrmLib.c
patching file lib/Xm/VendorS.c
Hunk #2 FAILED at 525.
1 out of 2 hunks FAILED -- saving rejects to file lib/Xm/VendorS.c.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
```

**Comment by dunn** [comment]
Do you know if that patch has been applied upstream, or if there's a refreshed patch we need to include?

**Comment by smalyshev** [comment]
@dunn I don't know, the patch just fails, I don't know Motif build enough to see what's missing.

**Comment by dunn** [comment]
Removing the patch causes the build to fail with the error reported here: http://bugs.motifzone.net/long_list.cgi?buglist=1625

Given that it's been left open for three and a half years without comment, I think the conclusion is that OpenMotif is not supported on macOS.

**Comment by dunn** [comment]
@smalyshev you should be able to install it now!

**Comment by smalyshev** [comment]
yes, no more patch failures, thank you!
