### ISSUE TITLE
Remove imake

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-x11#288]
Imake is an obsolete build system, which was removed from X11 as of X11R7.0 (in December 2005). The only package in homebrew that requires `imake` is `homebrew-science/transfig`. When `transfig` is updated to version 3.2.6a (https://github.com/Homebrew/homebrew-science/pull/4871), which doesn't use imake anymore, we should remove `imake` from the repo.

**Comment by fxcoudert** [comment]
`transfig` has been updated, thus `imake` should removed or moved to the boneyard.

**Comment by MikeMcQuaid** [comment]
Let's wait and see what the analytics usage numbers are like. It's possible that some people still need this for legacy build systems even if we don't need it for other formulae.

**Comment by MikeMcQuaid** [comment]
This was migrated to homebrew/core because it's still used (for now).
