### ISSUE TITLE
Error installing inkscape

### ISSUE THREAD

**Issue by extrinsicmedia** [Homebrew/homebrew-x11#44]
Getting this error despite having aclocal-1.14 at this location in Cellar:
`/opt/boxen/homebrew/Cellar/automake/1.14.1/bin/aclocal-1.14`

Error:
`CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /private/tmp/inkscape20150328-93619-1rbwbjq/inkscape-0.48.5/missing aclocal-1.14`
`/private/tmp/inkscape20150328-93619-1rbwbjq/inkscape-0.48.5/missing: line 81: aclocal-1.14: command not found`
`WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>`
`make: *** [aclocal.m4] Error 127`

**Comment by mistydemeo** [comment]
Please follow the [troubleshooting guide](http://git.io/brew-troubleshooting) and post all of the requested diagnostics, thanks!

**Comment by pathawks** [comment]
Duplicate of #30

**Comment by extrinsicmedia** [comment]
The fix proposed by @sandbagger in #30 solves my issue.  Closing ticket.
