### ISSUE TITLE
what are the conditions to get merged?

### ISSUE THREAD

**Issue by robotvert** [Homebrew/homebrew-x11#45]
Hi,

I've submitted a [PR a while ago](/Homebrew/homebrew-x11/pull/37), it passes the tests and locally there's no issues whatsoever (it's a minor version bump) but no one with write access seems to be willing to merge it.
Seeing there are other PRs that have been waiting to get merged while others have indeed been merged recently, can someone tell me what are the conditions required to get the thing in master?

When those recipes were in the main repo they'd get merged very quickly, hence my question.

**Comment by DomT4** [comment]
Apologies. It's not likely to be so much unwillingness to merge, It's more likely that your PR got absolutely buried underneath Homebrew's PR. The group overview details every forking, starring, issue and PR created for every repo in the organisation; it can quickly get hectic in something as popular and vast as Homebrew. One of the maintainers will pick it up soonish, I expect. You can always ping them individually and ask - Although that's not always easy to notice either.

**Comment by robotvert** [comment]
Thanks for the explanation.

I somehow assumed that a few people were focused on the x11 tap, seems it's not the case eh :sweat_smile:

**Comment by DomT4** [comment]
Not every tap has individual maintainers. The ones that do are often because they're quite specialised areas (nginx, php, apache, etc). There are 7 core maintainers with write access across all the repositories.

**Comment by robotvert** [comment]
closing this for now because whether it's opened or closed doesn't seem to change anything to the "merges occur randomly in this tap" issue.
