### ISSUE TITLE
/usr/bin/tar can't unpack new atari++ tarball

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew-x11#51]
It takes gnu-tar to unpack <http://www.xl-project.com/download/atari++_1.73.tar.gz> properly; built-in tar gives this error:

```
tar xf /Library/Caches/Homebrew/atari++-1.73.tar.gz
atari++/winmain.cpp: Can't create 'atari++/winmain.cpp'
tar: Error exit delayed from previous errors.
```

There's no way to customize how Homebrew unpacks things, is there?

**Comment by mistydemeo** [comment]
Could you report it to the developers? It seems like a potential problem with the tarball if bsdtar can't open it.

**Comment by dunn** [comment]
I let him know; no reply yet.

**Comment by dunn** [comment]
I guess we'll have to pass on this version.
