### ISSUE TITLE
Failed to install tiger-vnc

### ISSUE THREAD

**Issue by pythianmantoani** [Homebrew/homebrew-x11#57]
I am having issue when try to install tiger-vnc error on make as can se below, anyone had same issue?

Mantoani:~ Mantoani$ brew install homebrew/x11/tiger-vnc
==> Installing tiger-vnc from homebrew/homebrew-x11
==> Downloading https://github.com/TigerVNC/tigervnc/archive/v1.4.0.tar.gz
######################################################################## 100.0%
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tiger-vnc/1.4.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev 
==> make install
[ 15%] Built target Xregion
1 error generated.
make[2]: *** [common/os/CMakeFiles/os.dir/tls.cxx.o] Error 1
make[1]: *** [common/os/CMakeFiles/os.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-x11/issues

These open issues may also help:
tiger-vnc: re-adding formula with x11 dep dropped (https://github.com/Homebrew/homebrew/pull/35425)
Mantoani:~ Mantoani$ 

https://gist.github.com/9021cdb4a59707128280

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please read this and post the requested logs, thanks!

**Comment by pythianmantoani** [comment]
Hi logs are located here

https://gist.github.com/9021cdb4a59707128280

**Comment by pythianmantoani** [comment]
Mantoani:~ Mantoani$ brew update
Already up-to-date.
Mantoani:~ Mantoani$ brew doctor
Your system is ready to brew.
Mantoani:~ Mantoani$

**Comment by DomT4** [comment]
This should be fixed now. It was a problem with Apple's CLT package a couple of releases ago. Please request reopening if the problem persists after ensuring your CLT is up-to-date.
