### ISSUE TITLE
gtk+3 has now only the quartz backend

### ISSUE THREAD

**Issue by tschoonj** [Homebrew/homebrew-x11#65]
Gtk 3.16.0 introduced the dependency on libepoxy, which supports quartz only (Homebrew/homebrew#38972). This in turn disables the X11 backend leaving only the quartz backend.

This impacts all formulas in this tap that depend on gtk+3: they should have their X11 dependency stripped and probably moved back into the main Homebrew tap.

Any thoughts on this?

**Comment by DomT4** [comment]
We'll consider things on a case-by-case basis here. GUI-by-default stuff will remain in X11 for now; we're considering a GUI tap for this sort of thing but haven't entirely decided yet.
