### ISSUE TITLE
xclip not building

### ISSUE THREAD

**Issue by marceljj** [Homebrew/homebrew-x11#71]
It builds on one of my Macs but not on the others. I get this error:

==> Installing xclip from homebrew/homebrew-x11
==> Downloading https://downloads.sourceforge.net/project/xclip/xclip/0.12/xclip
Already downloaded: /Library/Caches/Homebrew/xclip-0.12.tar.gz
==> ./configure --prefix=/usr/local/Cellar/xclip/0.12
==> make install
) _X_ATTRIBUTE_PRINTF(2,3);
  ^
14 errors generated.
make: *** [xclip.o] Error 1
make: *** Waiting for unfinished jobs....
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-x11/issues

MacPorts is also installed on the computer where it works, so that can't be it. I have uninstalled homebrew and reinstalled it, and it still doesn't compile. Any help?

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please read this and provide all of the requested diagnostics, thanks!

**Comment by marceljj** [comment]
OK, so I read that unbrewed dylib files can cause issues, and running "brew doctor" does show unbrewed dylib files, but I installed them all manually from things separate from Homebrew.

I uninstalled all of them (and reinstalled the homebrew versions) and brew doctor only mentioned the existence of MacPorts (the computer on which xclip compiles on also has it though). Yet I still have the same issue. Here's what I get from "brew install -v xclip":

<code>Marcels-Mac:lib marceljj$ brew install -v xclip
==> Installing xclip from homebrew/homebrew-x11
==> Downloading https://downloads.sourceforge.net/project/xclip/xclip/0.12/xclip-0.12.tar.gz
Already downloaded: /Library/Caches/Homebrew/xclip-0.12.tar.gz
==> Verifying xclip-0.12.tar.gz checksum
tar xf /Library/Caches/Homebrew/xclip-0.12.tar.gz
==> ./configure --prefix=/usr/local/Cellar/xclip/0.12
checking for gcc... clang
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for strip... strip
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking X11/Xmu/Atoms.h usability... no
checking X11/Xmu/Atoms.h presence... yes
configure: WARNING: X11/Xmu/Atoms.h: present but cannot be compiled
configure: WARNING: X11/Xmu/Atoms.h:     check for missing prerequisite headers?
configure: WARNING: X11/Xmu/Atoms.h: see the Autoconf documentation
configure: WARNING: X11/Xmu/Atoms.h:     section "Present But Cannot Be Compiled"
configure: WARNING: X11/Xmu/Atoms.h: proceeding with the preprocessor's result
configure: WARNING: X11/Xmu/Atoms.h: in the future, the compiler will take precedence
checking for X11/Xmu/Atoms.h... yes
checking X11/Intrinsic.h usability... no
checking X11/Intrinsic.h presence... yes
configure: WARNING: X11/Intrinsic.h: present but cannot be compiled
configure: WARNING: X11/Intrinsic.h:     check for missing prerequisite headers?
configure: WARNING: X11/Intrinsic.h: see the Autoconf documentation
configure: WARNING: X11/Intrinsic.h:     section "Present But Cannot Be Compiled"
configure: WARNING: X11/Intrinsic.h: proceeding with the preprocessor's result
configure: WARNING: X11/Intrinsic.h: in the future, the compiler will take precedence
checking for X11/Intrinsic.h... yes
checking for XmuClientWindow in -lXmu... yes
configure: creating ./config.status
config.status: creating Makefile
==> make install
clang -g -O2 -Wall  -DPACKAGE_NAME=\"xclip\" -DPACKAGE_TARNAME=\"xclip\" -DPACKAGE_VERSION=\"0.12\" -DPACKAGE_STRING=\"xclip\ 0.12\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBXMU=1 -o xclib.o -c xclib.c
clang -g -O2 -Wall  -DPACKAGE_NAME=\"xclip\" -DPACKAGE_TARNAME=\"xclip\" -DPACKAGE_VERSION=\"0.12\" -DPACKAGE_STRING=\"xclip\ 0.12\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBXMU=1 -o xcprint.o -c xcprint.c
clang -g -O2 -Wall  -DPACKAGE_NAME=\"xclip\" -DPACKAGE_TARNAME=\"xclip\" -DPACKAGE_VERSION=\"0.12\" -DPACKAGE_STRING=\"xclip\ 0.12\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBXMU=1 -o xclip.o -c xclip.c
mkdir -p /usr/local/Cellar/xclip/0.12/share/man/man1
/usr/bin/install -c -m 644 xclip.1 xclip-copyfile.1 /usr/local/Cellar/xclip/0.12/share/man/man1
In file included from xclip.c:28:
In file included from /opt/X11/include/X11/Xmu/Atoms.h:35:
/opt/X11/include/X11/Intrinsic.h:1178:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1322:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1389:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1396:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1420:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1472:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1495:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1569:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1590:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1601:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1612:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1627:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1642:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/opt/X11/include/X11/Intrinsic.h:1865:3: error: expected function body after function declarator
) _X_ATTRIBUTE_PRINTF(2,3);
  ^
14 errors generated.
make: *** [xclip.o] Error 1
make: *** Waiting for unfinished jobs....
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
==> Formula
Tap: homebrew/homebrew-x11
Path: /usr/local/Library/Taps/homebrew/homebrew-x11/xclip.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: db091b65a57e983c76316ae312773a8697f5a7a6
Last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit penryn
OS X: 10.10.3-x86_64
Xcode: 6.3.1
CLT: 6.3.1.0.1.1429149539
Clang: 6.1 build 602
MacPorts/Fink: /opt/local/bin/port
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_45
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/opt/X11/include:/opt/X11/include/freetype2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /opt/X11/lib:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10:/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig
ACLOCAL_PATH: /usr/local/share/aclocal:/opt/X11/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: xclip 0.12 did not build
Logs:
     /Users/marceljj/Library/Logs/Homebrew/xclip/01.configure
     /Users/marceljj/Library/Logs/Homebrew/xclip/01.configure.cc
     /Users/marceljj/Library/Logs/Homebrew/xclip/02.make
     /Users/marceljj/Library/Logs/Homebrew/xclip/02.make.cc
     /Users/marceljj/Library/Logs/Homebrew/xclip/config.log
</code>

Sorry if the formattings off, I'm not good at it. :P

Thanks for your help so far, and I hope I can get this issue resolved.

**Comment by DomT4** [comment]
Can you do `brew gist-logs xclip` please? It'll clear up the formatting and provide other useful `brew` information. Thanks!

**Comment by marceljj** [comment]
Sorry, I can't - I reinstalled OS X, but on the plus side it compiled with a new install. I guess I just messed up something by myself. Thanks for the help though!

**Comment by DomT4** [comment]
No worries, Glad it's working now! Thanks for closing the bug report :tada:
