### ISSUE TITLE
zenity-3.14.0 from build from source

### ISSUE THREAD

**Issue by seeitbelieveit** [Homebrew/homebrew-x11#74]
1 error generated.
make[2]: *** [zenity-entry.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

After building every package possible from source

**Comment by mistydemeo** [comment]
Please read the [troubleshooting guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting) and post all of the requested diagnostics, thanks!

**Comment by DomT4** [comment]
Closing as stale.
