### ISSUE TITLE
Yarp compilation failed in Yosemite

### ISSUE THREAD

**Issue by Dazzid** [Homebrew/homebrew-x11#76]
Hi All!
I'm trying to compile yarp for Os X (Yosemite) but I'm having this issue:

ws120582:~ David$ brew install yarp
==> Installing yarp from homebrew/homebrew-x11
==> Downloading https://github.com/robotology/yarp/archive/v2.3.63.tar.gz
Already downloaded: /Library/Caches/Homebrew/yarp-2.3.63.tar.gz
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/yarp/2.3.63 -DCMAKE_BUILD_TYPE=Release -DCMAKE_
    linked by target "gyarpmanager" in directory /tmp/yarp20150522-31453-8yzzi8/yarp-2.3.63/src/yarpmanager/gymanager

-- Configuring incomplete, errors occurred!
See also "/tmp/yarp20150522-31453-8yzzi8/yarp-2.3.63/CMakeFiles/CMakeOutput.log".
See also "/tmp/yarp20150522-31453-8yzzi8/yarp-2.3.63/CMakeFiles/CMakeError.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-x11/issues

No idea how to make it compile properly.
Thanks a lot for the help
David

**Comment by dunn** [comment]
Could you post `brew gist-logs yarp`?

**Comment by DomT4** [comment]
Ping?
