### ISSUE TITLE
easy-tag: missing icons after version bump

### ISSUE THREAD

**Issue by robotvert** [Homebrew/homebrew-x11#89]
Most likely [this commit](https://github.com/Homebrew/homebrew-x11/commit/2004b4ce8f712bd3d753553b09907a1c50473a67) is the culprit and the major GTK version bump is to blame.

A picture is worth a thousand words so here goes:
![screen shot 2015-06-19 at 09 47 00](https://cloud.githubusercontent.com/assets/514215/8249282/d92112c4-1668-11e5-8d75-773cfbd128bb.png)

True that the version up until now had a couple of icons missing (in the input boxes to apply a change to multiple files) but IIRC most, if not all, the toolbar icons were here.

On a side note, was the upgrade to 2.3.7 necessary? 2.3.x is the unstable branch, the stable one is 2.2.x.

@tschoonj any thoughts?

**Comment by tschoonj** [comment]
Sorry didn't realize that this was the unstable branch. I rely too much on `audit --strict`...
@DomT4 Can we still downgrade this? I guess it will require users to uninstall this new version first as it won't show up as outdated.

Interestingly I do not have the icons missing here. probably a `gtk-update-icon-cache` thing that can be fixed with a post_install call:

Could you execute: 

`gtk3-update-icon-cache -f -t `brew --prefix`/share/icons/hicolor"

and see if the icons are still missing afterwards?

Thanks!

**Comment by robotvert** [comment]
Apart from the icons missing issue the unstable branch _seems_ rather solid, it's been in dev for months now after all, so I don't think a downgrade is strictly necessary. Was just wondering if it was forced upon us because of the GTK3 dep.

Could you reformat the command you want me to run? The \` and " are unbalanced and since I know next to nothing of GTK tools I'm not sure where these are supposed to start and end... :sweat_smile:

**Comment by tschoonj** [comment]
Ok I fixed the command, sorry about that.

I just assumed that 2.3.7 would be a stable release. Part of the transitioning to gtk-quartz involved checking for packages that started supporting gtk+3 instead of gtk+2, and if so switch them to the former.  

In this case only gtk+3 is supported for easy-tag 2.3.7 so I had no choice but to make the switch.

**Comment by robotvert** [comment]
```
gtk3-update-icon-cache -f -t `brew --prefix`/share/icons/hicolor
gtk3-update-icon-cache: Cache file created successfully.
```
but it didn't solve the issue... :cry:

**Comment by tschoonj** [comment]
Do you get error messages in the terminal regarding these icons when you launch easytag?

If so, copy-paste them please

**Comment by robotvert** [comment]
ah, sorry, should have included those from the beginning. I've always had a couple of warnings when launching easytag so I usually ignore them..

```
easytag

(easytag:13811): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
2015-06-19 11:19:33.272 easytag[13811:48257] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.

(easytag:13811): GLib-GObject-WARNING **: The property GtkWidget:margin-left is deprecated and shouldn't be used anymore. It will be removed in a future version.

(easytag:13811): GLib-GObject-WARNING **: The property GtkWidget:margin-right is deprecated and shouldn't be used anymore. It will be removed in a future version.
```

Before you ask, the output of `locale` is
```
LANG="en_us.UTF-8"
LC_COLLATE="en_us.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_us.UTF-8"
LC_MONETARY="en_us.UTF-8"
LC_NUMERIC="en_us.UTF-8"
LC_TIME="en_us.UTF-8"
LC_ALL=
```

**Comment by tschoonj** [comment]
Do you have `gnome-icon-theme` installed?

**Comment by robotvert** [comment]
I didn't and installing it solved the issue. 
Me thinks it should be added to the formula's dependencies from now.

Thanks for the help!

**Comment by tschoonj** [comment]
You're welcome. Honestly I think it should be added to the dependency-list of gtk+3 as it is pretty useless otherwise after they removed all the default icons a couple of versions ago.

@mikemcquaid @DomT4 What do you think?

**Comment by mikemcquaid** [comment]
@tschoonj Makes sense, at least being `:recommended`. Mind making a PR? Thanks!

**Comment by tschoonj** [comment]
Hmm... this way you will get a circular dependency as `gnome-icon-theme` has a build-time dependency on `gtk+3` for `gtk-update-icon-cache`.

An alternative would be to treat `gnome-icon-theme` as a resource in `gtk+3`.  People would still be able to install their own icon-themes and use them after updating the appropriate config file in the home folder.

What do you think?

**Comment by mikemcquaid** [comment]
> An alternative would be to treat gnome-icon-theme as a resource in gtk+3. People would still be able to install their own icon-themes and use them after updating the appropriate config file in the home folder.
> 
> What do you think?

Sounds good :+1:

**Comment by DomT4** [comment]
> @DomT4 Can we still downgrade this? I guess it will require users to uninstall this new version first as it won't show up as outdated.

Yes, we can if necessary. Users who have already upgraded will be "stuck" on the development version unless they `brew reinstall` it. Will it still work as expected, given all the other changes made in that PR beyond the version change?

**Comment by DomT4** [comment]
Have reopened this until we decide whether to keep/revert.

**Comment by tschoonj** [comment]
Well the OP says it looks stable enough. It's already the seventh release in their unstable branch so I guess they're close to releasing the new stable version anyway.

If we had to revert that would mean it becomes dependent again on `gtk+`.

**Comment by mikemcquaid** [comment]
I think it'd be good to keep this using `gtk3+`, fix the icon issue and `revision` it.

**Comment by DomT4** [comment]
Alright, let's keep it on unstable until the next available stable release.

I think https://github.com/Homebrew/homebrew/pull/40888 should solve the icon issue.
